"""Synthetic encoder fixture; no model downloads or user data.

Run with the pinned mlx-vlm fec3f50379bb2cb0760ef3c8a68ebce9585e4d97
environment used by SightRoll's EmbeddingGemma 2 reference pilot.
"""
import hashlib
import json
from pathlib import Path

import mlx.core as mx
import numpy as np
from mlx.utils import tree_flatten
from mlx_vlm.models.embedding_gemma2.config import ModelConfig
from mlx_vlm.models.embedding_gemma2.embedding_gemma2 import Model


def main():
    root = Path(__file__).resolve().parents[2] / "Tests/MLXLMTests/Resources/EmbeddingGemma2"
    root.mkdir(parents=True, exist_ok=True)
    configuration = {
        "model_type": "embedding_gemma2",
        "text_config": {
            "model_type": "embedding_gemma2_text", "vocab_size": 32,
            "hidden_size": 8, "intermediate_size": 16, "num_hidden_layers": 2,
            "num_attention_heads": 2, "num_key_value_heads": 1, "head_dim": 4,
            "hidden_size_per_layer_input": 4, "embedding_dim": 6,
            "rms_norm_eps": 1e-6, "sliding_window": 2, "attention_bias": False,
            "pad_token_id": 0, "bos_token_id": 2, "eos_token_id": 1,
            "layer_types": ["sliding_attention", "full_attention"],
            "per_layer_config": {"01": {"head_dim": 8, "num_key_value_heads": 1}},
            "rope_parameters": {
                "sliding_attention": {"rope_theta": 10000, "rope_type": "default"},
                "full_attention": {"rope_theta": 1000000, "rope_type": "default"},
            },
        },
        "image_token_id": 28, "audio_token_id": 29, "video_token_id": 30,
        "boi_token_id": 24, "eoi_token_id": 25, "boa_token_id": 26, "eoa_token_id": 27,
    }
    model = Model(ModelConfig.from_dict(configuration))
    weights = {}
    for key, value in tree_flatten(model.parameters()):
        seed = int.from_bytes(hashlib.sha256(key.encode()).digest()[:4], "little")
        rng = np.random.default_rng(seed)
        values = rng.normal(0, 0.12, size=value.shape).astype(np.float32)
        if key.endswith("norm.weight") or "layernorm.weight" in key:
            values += 1
        if key.endswith("layer_scalar"):
            values[:] = 0.9
        weights[key] = mx.array(values)
    mx.save_safetensors(str(root / "tiny-float32.safetensors"), weights)
    tokens = mx.array([[2, 4, 8, 1, 0], [2, 8, 4, 6, 1]])
    valid = tokens != 0
    expected = {"tokens": tokens, "valid": valid}
    for dtype, name in [(mx.float32, "float32"), (mx.bfloat16, "bf16")]:
        model.load_weights([(k, v.astype(dtype)) for k, v in weights.items()])
        expected[name] = model(tokens, attention_mask=valid).text_embeds
        x = mx.arange(2 * 2 * 3 * 8, dtype=mx.float32).reshape(2, 2, 3, 8).astype(dtype) / 31
        from mlx_vlm.models.embedding_gemma2.language import RotaryEmbedding
        expected[f"rotary_{name}"] = RotaryEmbedding(8, 1000000)(x, mx.array([[511, 512, 513], [2047, 2048, 2049]]))
    mx.eval(expected)
    mx.save_safetensors(str(root / "expected.safetensors"), expected)
    from PIL import Image
    from transformers.models.gemma4.feature_extraction_gemma4 import Gemma4AudioFeatureExtractor
    rgb = np.random.default_rng(73).integers(0, 256, (11, 13, 3), dtype=np.uint8)
    processor = {"rgb": mx.array(rgb)}
    for height, width in [(15, 17), (7, 5), (11, 17), (7, 13)]:
        resized = Image.fromarray(rgb).resize((width, height), Image.Resampling.BICUBIC)
        processor[f"rgb_{height}_{width}"] = mx.array(np.asarray(resized))
    samples = (np.sin(np.arange(16000 * 2) * (2 * np.pi * 440 / 16000)) * 0.25).astype(np.float32)
    features = Gemma4AudioFeatureExtractor()([samples], return_tensors="np", sampling_rate=16000)
    processor["waveform"] = mx.array(samples)
    processor["mel"] = mx.array(np.asarray(features["input_features"]))
    processor["mel_valid"] = mx.array(np.asarray(features["input_features_mask"]))
    mx.save_safetensors(str(root / "processor.safetensors"), processor)
    (root / "config.json").write_text(json.dumps(configuration, indent=2) + "\n")
    (root / "PROVENANCE.md").write_text(
        "Synthetic deterministic weights generated by `tools/EmbeddingGemma2/generate_fixture.py`.\n"
        "Reference: mlx-vlm fec3f50379bb2cb0760ef3c8a68ebce9585e4d97; MLX 0.32.3.\n"
        "Exercises bidirectional/full and inclusive local attention, per-layer head overrides,\n"
        "projection-only PLE, padding, token projection, masked mean, and FP32 normalization.\n"
        "No pretrained weights or user-derived data.\n")


if __name__ == "__main__":
    main()
